version: '3.8'
services:
  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - streaming-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # Eureka Server - ✅ CORREGIDO
  eureka-server:
    build: ./eureka-server  # ✅ Sangría correcta
    ports:
      - "8761:8761"
    networks:
      - streaming-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    restart: unless-stopped

  # Cloud Gateway - ✅ SIMPLIFICADO
  cloud-gateway:
    build: ./cloud-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - streaming-network  # ✅ Eliminar config extra
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    restart: on-failure

  # Movie Search Service
  movie-search-service:
    build: ./movie-search-service
    ports:
    - "8081:9090"
    depends_on:
      - elasticsearch
      - eureka-server
    networks:
      - streaming-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9200
      - SPRING_DATA_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    restart: on-failure

  # Movie Operation Service - ✅ SIMPLIFICADO
  movie-operation-service:
    build: ./movie-operation-service
    depends_on:
      - eureka-server
    networks:
      - streaming-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    restart: on-failure

volumes:
  elasticsearch_data:

networks:
  streaming-network:
    driver: bridge
